name: Test Odoo Container

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 7 15 * *"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ubuntu_version: "20.04"
            odoo_version: "11.0"
            python_version: "3.5"
          - ubuntu_version: "20.04"
            odoo_version: "12.0"
            python_version: "3.5"
          - ubuntu_version: "20.04"
            odoo_version: "13.0"
            python_version: "3.6"
          - ubuntu_version: "20.04"
            odoo_version: "14.0"
            python_version: "3.8"
          - ubuntu_version: "20.04"
            odoo_version: "15.0"
            python_version: "3.8"
          - ubuntu_version: "22.04"
            odoo_version: "16.0"
            python_version: "3.10"
          - ubuntu_version: "22.04"
            odoo_version: "17.0"
            python_version: "3.10"
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fr33co/odootests:${{ matrix.odoo_version }}
          platforms: linux/amd64
          build-args: |
            ubuntu_version=${{ matrix.ubuntu_version }}
            odoo_version=${{ matrix.odoo_version }}
            python_version=${{ matrix.python_version }}
            timezone=America/Bogota
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=inline